#!/bin/bash
rm -f *.bin *.elf *.o
~/armgcc/bin/arm-none-eabi-as -mcpu=cortex-m0 -o m0s.o m0s.asm
~/armgcc/bin/arm-none-eabi-ld -Ttext 0x8000000 m0s.o -o m0s.elf
~/armgcc/bin/arm-none-eabi-objcopy -S -O binary m0s.elf m0s.bin
~/armgcc/bin/arm-none-eabi-size m0s.elf
rm -f *.elf *.o

