#!/bin/bash
rm -f *.elf *.o
~/armgcc/bin/arm-none-eabi-gcc -fno-builtin-free -fno-builtin-memset -mcpu=cortex-m0 -mthumb -c -o2 -Wall demo.c -o demo.o
~/armgcc/bin/arm-none-eabi-as -mcpu=cortex-m0 -o m0s.o m0s.asm
~/armgcc/bin/arm-none-eabi-ld -Ttext 0x8000000 m0s.o demo.o -o m0s.elf
~/armgcc/bin/arm-none-eabi-objcopy -S -O binary m0s.elf m0s-demo.bin
~/armgcc/bin/arm-none-eabi-size m0s.elf
rm -f *.elf *.o
